export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRANCH_ADMIN: 'BRANCH_ADMIN',
  EMPLOYEE: 'EMPLOYEE',
};

export const PERMISSIONS = {
  BILLING: 'BILLING',
  HOLD_BILL: 'HOLD_BILL',
  RETURNS: 'RETURNS',
  CREDIT_SALE: 'CREDIT_SALE',
  STOCK_ADJUST: 'STOCK_ADJUST',
  EMPLOYEE_MANAGE: 'EMPLOYEE_MANAGE',
  BRANCH_MANAGE: 'BRANCH_MANAGE',
  ADMIN_MANAGE: 'ADMIN_MANAGE',
  PRODUCT_MASTER: 'PRODUCT_MASTER',
  TRANSFER_APPROVE: 'TRANSFER_APPROVE',
  GLOBAL_SETTINGS: 'GLOBAL_SETTINGS',
  GLOBAL_REPORTS: 'GLOBAL_REPORTS',
  CRM_MANAGE: 'CRM_MANAGE',
  LEDGER_VIEW: 'LEDGER_VIEW',
  PAYMENTS_MANAGE: 'PAYMENTS_MANAGE',
  RECEIPTS_MANAGE: 'RECEIPTS_MANAGE',
  PURCHASE_MANAGE: 'PURCHASE_MANAGE',
  SUPPLIER_MANAGE: 'SUPPLIER_MANAGE',
  EXPENSE_MANAGE: 'EXPENSE_MANAGE',
  REPORTS_VIEW: 'REPORTS_VIEW',
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  PRICE_EDIT: 'PRICE_EDIT',
  DISCOUNT_EDIT: 'DISCOUNT_EDIT',
  TRANSFER_CREATE: 'TRANSFER_CREATE',
  TRANSFER_VIEW: 'TRANSFER_VIEW',
  TRANSFER_DISPATCH: 'TRANSFER_DISPATCH',
  TRANSFER_RECEIVE: 'TRANSFER_RECEIVE',
  TARGET_MANAGE: 'TARGET_MANAGE',
  ATTENDANCE_MANAGE: 'ATTENDANCE_MANAGE',
  PAYROLL_MANAGE: 'PAYROLL_MANAGE',
};

export const ROLE_HOME_ROUTE = {
  [ROLES.EMPLOYEE]: '/(employee)/billing',
  [ROLES.BRANCH_ADMIN]: '/(branch-admin)/dashboard',
  [ROLES.SUPER_ADMIN]: '/(super-admin)/dashboard',
};

export default ROLES;
